[workspace]
resolver = "2"
members = ["crates/goviet-engine", "crates/goviet-win", "crates/goviet-cli"]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["Zenix Labs <https://zenix.vn>"]
repository = "https://github.com/zenix-vn/go-viet-windows"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
